"""
Narrative Analysis Report Generator

Creates human-readable markdown reports from website analysis
"""

from pathlib import Path
from typing import Dict
from datetime import datetime


class ReportGenerator:
    """Generates markdown reports from narrative analysis"""

    def __init__(self, analysis_data: Dict):
        self.data = analysis_data

    def generate_markdown(self) -> str:
        """Generate a comprehensive markdown report"""

        report = f"""# Narrative Analysis Report

**Generated**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

## Executive Summary

{self._summary_section()}

## Value Propositions

{self._value_props_section()}

## Key Statistics & Proof Points

{self._stats_section()}

## Feature Claims

{self._features_section()}

## Customer Testimonials

{self._testimonials_section()}

## Narrative Structure

{self._narrative_units_section()}

## Insights & Recommendations

{self._insights_section()}

---
*Generated by Principal Narrative Agent*
"""
        return report

    def _summary_section(self) -> str:
        """Generate summary section"""
        s = self.data['summary']
        return f"""
This analysis identified:
- **{s['total_claims']}** distinct claims across all content
- **{s['total_proof']}** proof points (stats, testimonials, case studies)
- **{s['total_personas']}** customer personas
- **{s['total_narrative_units']}** narrative units (problem → solution → proof)
- **{s['total_stats']}** key statistics

"""

    def _value_props_section(self) -> str:
        """Extract and display value propositions"""
        value_props = [c for c in self.data['claims'] if c['type'] == 'value_prop']

        if not value_props:
            return "*No value propositions identified*\n"

        output = "\n### Main Value Propositions\n\n"
        for vp in value_props[:5]:
            output += f"- **{vp['text']}**\n"
            output += f"  - *Location*: {vp['location']}\n"
            output += f"  - *Confidence*: {vp['confidence']:.0%}\n\n"

        return output

    def _stats_section(self) -> str:
        """Display key statistics"""
        stats = self.data.get('stats', {})

        if not stats:
            return "*No statistics found*\n"

        output = "\n### Key Metrics\n\n"
        output += "| Stat | Context |\n"
        output += "|------|----------|\n"

        for stat, context in stats.items():
            # Clean up context
            context_clean = context.replace('\n', ' ').strip()[:100]
            output += f"| **{stat}** | {context_clean}... |\n"

        return output + "\n"

    def _features_section(self) -> str:
        """Display feature claims"""
        features = [c for c in self.data['claims'] if c['type'] == 'feature']

        if not features:
            return "*No features identified*\n"

        output = "\n### Core Features\n\n"

        # Group by location
        by_location = {}
        for f in features:
            loc = f['location']
            if loc not in by_location:
                by_location[loc] = []
            by_location[loc].append(f)

        for location, feats in by_location.items():
            output += f"\n**{location}**:\n"
            for f in feats[:5]:  # Limit to 5 per location
                # Extract just the feature name if format is "Name: Description"
                text = f['text']
                if ':' in text:
                    parts = text.split(':', 1)
                    output += f"- **{parts[0].strip()}**: {parts[1].strip()[:80]}...\n"
                else:
                    output += f"- {text[:100]}...\n"

        return output

    def _testimonials_section(self) -> str:
        """Display customer testimonials"""
        testimonials = [p for p in self.data['proof'] if p['type'] == 'testimonial']

        if not testimonials:
            return "*No testimonials found*\n"

        output = "\n### Customer Quotes\n\n"

        for t in testimonials[:5]:  # Top 5
            output += f"> {t['text'][:200]}...\n\n"
            if t.get('source'):
                output += f"*— {t['source']}*\n\n"
            output += f"*Found in: {t['location']}*\n\n"
            output += "---\n\n"

        return output

    def _narrative_units_section(self) -> str:
        """Display narrative structure"""
        units = self.data.get('narrative_units', [])

        if not units:
            return "*No narrative units identified*\n"

        output = "\n### Narrative Patterns (Problem → Solution)\n\n"

        for unit in units[:8]:  # Top 8
            output += f"\n#### {unit['title']}\n\n"
            if unit.get('problem'):
                output += f"**Problem**: {unit['problem'][:150]}...\n\n"
            if unit.get('solution'):
                output += f"**Solution**: {unit['solution'][:150]}...\n\n"
            output += f"*Location: {unit['location']}*\n\n"

        return output

    def _insights_section(self) -> str:
        """Generate insights and recommendations"""
        s = self.data['summary']

        insights = []

        # Check claim-to-proof ratio
        claim_count = s['total_claims']
        proof_count = s['total_proof']

        if proof_count > 0:
            ratio = claim_count / proof_count
            if ratio > 2:
                insights.append("⚠️ **High claim-to-proof ratio**: Consider adding more evidence to support claims")
            elif ratio < 0.5:
                insights.append("✅ **Strong proof foundation**: Claims are well-supported by evidence")

        # Check for statistics
        if s['total_stats'] < 3:
            insights.append("💡 **Limited quantitative proof**: Consider adding more specific metrics and statistics")
        else:
            insights.append(f"✅ **Strong quantitative proof**: {s['total_stats']} statistics found")

        # Check narrative structure
        if s['total_narrative_units'] > 10:
            insights.append("✅ **Rich narrative structure**: Strong problem → solution storytelling")
        elif s['total_narrative_units'] < 5:
            insights.append("💡 **Limited narrative flow**: Consider developing more problem → solution narratives")

        # Check personas
        if s['total_personas'] == 0:
            insights.append("⚠️ **No personas identified**: Testimonials may need better attribution")

        if not insights:
            insights.append("✅ **No major issues identified**")

        output = "\n"
        for insight in insights:
            output += f"- {insight}\n"

        output += "\n### Recommendations\n\n"
        output += "1. **Strengthen proof**: Ensure every major claim has supporting evidence\n"
        output += "2. **Narrative consistency**: Maintain problem → solution → proof pattern\n"
        output += "3. **Quantify impact**: Add more specific metrics where possible\n"
        output += "4. **Customer stories**: Include more detailed case studies and testimonials\n"

        return output

    def save_to_file(self, output_path: Path):
        """Save markdown report to file"""
        markdown = self.generate_markdown()

        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(markdown)

        print(f"\n📝 Markdown report saved to: {output_path}")
        return markdown


if __name__ == "__main__":
    import json

    # Load analysis data
    analysis_path = Path("/Users/julieallen/Desktop/codepilot-narrative-analysis.json")

    with open(analysis_path, 'r') as f:
        data = json.load(f)

    # Generate report
    generator = ReportGenerator(data)
    report = generator.generate_markdown()

    # Save to file
    output_path = Path("/Users/julieallen/Desktop/codepilot-narrative-report.md")
    generator.save_to_file(output_path)

    print("\n✅ Report generation complete!")
