/**
 * demo-data.js — Rich demo canon data for pre-populated workspaces.
 *
 * Each demo includes narrative units across all 6 layers with realistic
 * tensions, scopes, authors, and dependencies. Designed to showcase:
 *   - NCI scoring (not 100% — intentional drift/breaks)
 *   - Weighted NCI with layer breakdown
 *   - Contested/drifted units with prescriptive actions
 *   - Scope health (engineering vs. sales vs. marketing)
 *   - Graph structure and dependency chains
 *   - StoryMining-style coverage
 */

'use strict';

const DEMOS = {

  // ============================================================================
  // SaaS Demo: "TechFlow" — a collaboration platform with realistic tensions
  // ============================================================================
  saas: {
    name: 'TechFlow SaaS',
    description: 'Collaboration platform with narrative tensions between product and sales teams',
    skills: {
      brand: { company_name: 'TechFlow', never: ['synergy', 'ecosystem play'] },
      terminology: {
        preferred: ['collaboration', 'workspace', 'real-time', 'integrations'],
        forbidden: ['synergy', 'ecosystem play', 'move the needle'],
      },
      voice: {
        name: 'TechFlow Voice',
        summary: 'Clear, direct, developer-friendly. Technical confidence without jargon.',
        principles: ['Lead with clarity', 'Show, don\'t tell', 'Respect the reader\'s time'],
      },
    },
    units: [
      // ── Core Story (3 units) ──
      {
        id: 'tf-core-mission',
        type: 'core_story',
        assertion: 'TechFlow empowers distributed teams to collaborate as if they were in the same room.',
        dependencies: [],
        confidence: 1.0,
        author: 'Sarah Chen, CEO',
        authoredAt: '2025-09-15',
        scope: null,
        tensionIntent: null,
        contestedBy: [],
        intent: {},
        evidence_required: [],
      },
      {
        id: 'tf-core-wedge',
        type: 'core_story',
        assertion: 'Existing tools force teams to choose between sync and async — TechFlow bridges both.',
        dependencies: ['tf-core-mission'],
        confidence: 0.95,
        author: 'Sarah Chen, CEO',
        authoredAt: '2025-09-15',
        scope: null,
        tensionIntent: null,
        contestedBy: [],
        intent: {},
        evidence_required: [],
      },
      {
        id: 'tf-core-north-star',
        type: 'core_story',
        assertion: 'Every team interaction should generate organizational intelligence, not just messages.',
        dependencies: ['tf-core-mission'],
        confidence: 0.9,
        author: 'Sarah Chen, CEO',
        authoredAt: '2025-10-01',
        scope: null,
        tensionIntent: null,
        contestedBy: [],
        intent: {},
        evidence_required: [],
      },

      // ── Positioning (3 units, 1 CONTESTED) ──
      {
        id: 'tf-pos-category',
        type: 'positioning',
        assertion: 'TechFlow is the intelligent workspace for engineering-led organizations.',
        dependencies: ['tf-core-mission'],
        confidence: 0.9,
        author: 'Marcus Lee, CMO',
        authoredAt: '2025-10-10',
        scope: null,
        tensionIntent: null,
        contestedBy: ['tf-pos-enterprise'],
        intent: {},
        evidence_required: [],
      },
      {
        id: 'tf-pos-enterprise',
        type: 'positioning',
        assertion: 'TechFlow is the enterprise communication platform for Fortune 500 companies.',
        dependencies: ['tf-core-mission'],
        confidence: 0.85,
        author: 'Diana Reeves, VP Sales',
        authoredAt: '2025-11-20',
        scope: 'sales',
        tensionIntent: null,
        contestedBy: ['tf-pos-category'],
        intent: {},
        evidence_required: [],
      },
      {
        id: 'tf-pos-differentiator',
        type: 'positioning',
        assertion: 'Unlike Slack and Teams, TechFlow treats conversations as structured knowledge, not chat logs.',
        dependencies: ['tf-pos-category', 'tf-core-wedge'],
        confidence: 0.95,
        author: 'Marcus Lee, CMO',
        authoredAt: '2025-10-10',
        scope: null,
        tensionIntent: null,
        contestedBy: [],
        intent: {},
        evidence_required: [],
      },

      // ── Product Narrative (4 units, 1 DRIFTED with intent) ──
      {
        id: 'tf-prod-feed',
        type: 'product_narrative',
        assertion: 'The Activity Feed is the primary surface — all context flows through it.',
        dependencies: ['tf-pos-category'],
        confidence: 1.0,
        author: 'James Okafor, VP Product',
        authoredAt: '2025-10-15',
        scope: 'engineering',
        tensionIntent: null,
        contestedBy: [],
        intent: {},
        evidence_required: [],
      },
      {
        id: 'tf-prod-api-first',
        type: 'product_narrative',
        assertion: 'API-first architecture ensures every feature is programmable from day one.',
        dependencies: ['tf-pos-differentiator'],
        confidence: 0.95,
        author: 'Raj Patel, CTO',
        authoredAt: '2025-10-15',
        scope: 'engineering',
        tensionIntent: null,
        contestedBy: [],
        intent: {},
        evidence_required: [],
      },
      {
        id: 'tf-prod-dashboard',
        type: 'product_narrative',
        assertion: 'The Executive Dashboard is the primary surface — leadership needs high-level views.',
        dependencies: ['tf-pos-enterprise'],
        confidence: 0.8,
        author: 'Diana Reeves, VP Sales',
        authoredAt: '2025-12-01',
        scope: 'sales',
        tensionIntent: 'drift',
        contestedBy: [],
        intent: { drift: { reason: 'Sales team pitching dashboard-first to enterprise prospects' } },
        evidence_required: [],
      },
      {
        id: 'tf-prod-ai',
        type: 'product_narrative',
        assertion: 'AI-powered thread summaries turn conversations into searchable organizational memory.',
        dependencies: ['tf-core-north-star', 'tf-prod-feed'],
        confidence: 0.9,
        author: 'Raj Patel, CTO',
        authoredAt: '2025-11-01',
        scope: 'engineering',
        tensionIntent: 'evolution',
        contestedBy: [],
        intent: { evolution: { reason: 'New AI capabilities expanding the product vision' } },
        evidence_required: ['usage-data-ai-summaries'],
      },

      // ── Operational (3 units) ──
      {
        id: 'tf-ops-ship-weekly',
        type: 'operational',
        assertion: 'Engineering ships every Thursday with release notes and changelog.',
        dependencies: ['tf-prod-feed'],
        confidence: 1.0,
        author: 'Amy Zhang, Eng Manager',
        authoredAt: '2025-10-20',
        scope: 'engineering',
        tensionIntent: null,
        contestedBy: [],
        intent: {},
        evidence_required: [],
      },
      {
        id: 'tf-ops-sla',
        type: 'operational',
        assertion: '99.95% uptime SLA with 15-minute incident response for enterprise customers.',
        dependencies: ['tf-pos-enterprise'],
        confidence: 0.95,
        author: 'Diana Reeves, VP Sales',
        authoredAt: '2025-11-15',
        scope: 'sales',
        tensionIntent: null,
        contestedBy: [],
        intent: {},
        evidence_required: ['uptime-report-q4'],
      },
      {
        id: 'tf-ops-onboarding',
        type: 'operational',
        assertion: 'New customers self-onboard in under 10 minutes — no sales call required.',
        dependencies: ['tf-pos-category'],
        confidence: 0.85,
        author: 'James Okafor, VP Product',
        authoredAt: '2025-10-25',
        scope: null,
        tensionIntent: null,
        contestedBy: [],
        intent: {},
        evidence_required: ['onboarding-funnel-data'],
      },

      // ── Evidence (3 units, 1 UNKNOWN/missing evidence) ──
      {
        id: 'tf-ev-nps',
        type: 'evidence',
        assertion: 'Customer NPS is 72, up from 58 last quarter.',
        dependencies: ['tf-pos-category'],
        confidence: 1.0,
        author: 'Lisa Park, Data Lead',
        authoredAt: '2025-12-15',
        scope: null,
        tensionIntent: null,
        contestedBy: [],
        intent: {},
        evidence_required: [],
      },
      {
        id: 'tf-ev-growth',
        type: 'evidence',
        assertion: 'Revenue growing 40% YoY with 120% net dollar retention.',
        dependencies: ['tf-pos-enterprise'],
        confidence: 0.9,
        author: 'Diana Reeves, VP Sales',
        authoredAt: '2025-12-15',
        scope: 'sales',
        tensionIntent: null,
        contestedBy: [],
        intent: {},
        evidence_required: [],
      },
      {
        id: 'tf-ev-ai-adoption',
        type: 'evidence',
        assertion: 'AI summary feature used by 60% of active workspaces within first month.',
        dependencies: ['tf-prod-ai'],
        confidence: 0.7,
        author: null,
        authoredAt: null,
        scope: 'engineering',
        tensionIntent: null,
        contestedBy: [],
        intent: {},
        evidence_required: ['ai-adoption-dashboard'],
      },

      // ── Communication (3 units) ──
      {
        id: 'tf-comm-tagline',
        type: 'communication',
        assertion: '"Work together, anywhere" is the primary tagline across all channels.',
        dependencies: ['tf-core-mission'],
        confidence: 1.0,
        author: 'Marcus Lee, CMO',
        authoredAt: '2025-09-20',
        scope: null,
        tensionIntent: null,
        contestedBy: [],
        intent: {},
        evidence_required: [],
      },
      {
        id: 'tf-comm-dev-pitch',
        type: 'communication',
        assertion: 'Developer outreach leads with API-first messaging and code examples.',
        dependencies: ['tf-prod-api-first', 'tf-pos-differentiator'],
        confidence: 0.95,
        author: 'Marcus Lee, CMO',
        authoredAt: '2025-11-01',
        scope: 'marketing',
        tensionIntent: null,
        contestedBy: [],
        intent: {},
        evidence_required: [],
      },
      {
        id: 'tf-comm-enterprise-deck',
        type: 'communication',
        assertion: 'Enterprise sales deck emphasizes ROI, security, and compliance over developer experience.',
        dependencies: ['tf-pos-enterprise', 'tf-ops-sla'],
        confidence: 0.85,
        author: 'Diana Reeves, VP Sales',
        authoredAt: '2025-12-01',
        scope: 'sales',
        tensionIntent: 'deliberate_tension',
        contestedBy: [],
        intent: { deliberate_tension: { reason: 'Intentionally different messaging for enterprise buyers vs. developer audience' } },
        evidence_required: [],
      },
    ],
  },

  // ============================================================================
  // Nonprofit Demo: "Global Impact" — education nonprofit with alignment gaps
  // ============================================================================
  nonprofit: {
    name: 'Global Impact Foundation',
    description: 'Education nonprofit with tensions between field operations and fundraising',
    skills: {
      brand: { company_name: 'Global Impact Foundation', never: ['charity', 'third world'] },
      terminology: {
        preferred: ['communities', 'partnership', 'sustainable', 'evidence-based'],
        forbidden: ['charity', 'third world', 'beneficiaries', 'giving back'],
      },
      voice: {
        name: 'Global Impact Voice',
        summary: 'Warm but data-driven. Hopeful without being naive. Evidence over emotion.',
        principles: ['Center community voices', 'Lead with outcomes', 'Honest about challenges'],
      },
    },
    units: [
      // ── Core Story (2 units) ──
      {
        id: 'gi-core-mission',
        type: 'core_story',
        assertion: 'Every child deserves access to quality education regardless of where they are born.',
        dependencies: [],
        confidence: 1.0,
        author: 'Dr. Amara Osei, Executive Director',
        authoredAt: '2024-01-15',
        scope: null,
        tensionIntent: null,
        contestedBy: [],
        intent: {},
        evidence_required: [],
      },
      {
        id: 'gi-core-approach',
        type: 'core_story',
        assertion: 'We build lasting change by investing in local teachers and community-led schools.',
        dependencies: ['gi-core-mission'],
        confidence: 1.0,
        author: 'Dr. Amara Osei, Executive Director',
        authoredAt: '2024-01-15',
        scope: null,
        tensionIntent: null,
        contestedBy: [],
        intent: {},
        evidence_required: [],
      },

      // ── Positioning (3 units, 1 drifted) ──
      {
        id: 'gi-pos-evidence',
        type: 'positioning',
        assertion: 'We are the most evidence-based education nonprofit — every program decision is backed by data.',
        dependencies: ['gi-core-approach'],
        confidence: 0.95,
        author: 'Dr. Amara Osei, Executive Director',
        authoredAt: '2024-02-01',
        scope: null,
        tensionIntent: null,
        contestedBy: [],
        intent: {},
        evidence_required: [],
      },
      {
        id: 'gi-pos-scale',
        type: 'positioning',
        assertion: 'Operating in 14 countries with 800+ partner schools reaching 1.2 million students.',
        dependencies: ['gi-core-mission'],
        confidence: 0.9,
        author: 'Robert Kim, COO',
        authoredAt: '2024-06-01',
        scope: 'operations',
        tensionIntent: null,
        contestedBy: [],
        intent: {},
        evidence_required: ['annual-report-2025'],
      },
      {
        id: 'gi-pos-fundraising',
        type: 'positioning',
        assertion: 'Global Impact is the most efficient giving opportunity — 92 cents of every dollar reaches classrooms.',
        dependencies: ['gi-core-mission'],
        confidence: 0.8,
        author: 'Michelle Torres, VP Development',
        authoredAt: '2025-03-15',
        scope: 'fundraising',
        tensionIntent: 'drift',
        contestedBy: [],
        intent: { drift: { reason: 'Fundraising team emphasizing efficiency over impact to appeal to major donors' } },
        evidence_required: ['financial-audit-2025'],
      },

      // ── Product Narrative (3 units, 1 contested) ──
      {
        id: 'gi-prog-teacher',
        type: 'product_narrative',
        assertion: 'Teacher training is our highest-impact program — 18 months to measurable student outcomes.',
        dependencies: ['gi-core-approach', 'gi-pos-evidence'],
        confidence: 0.95,
        author: 'Dr. Fatima Al-Rashid, Programs Director',
        authoredAt: '2024-03-01',
        scope: 'programs',
        tensionIntent: null,
        contestedBy: [],
        intent: {},
        evidence_required: [],
      },
      {
        id: 'gi-prog-tech',
        type: 'product_narrative',
        assertion: 'Digital learning platforms are the future — tablets and connectivity for every classroom.',
        dependencies: ['gi-core-mission'],
        confidence: 0.7,
        author: 'Kevin Zhang, Tech Director',
        authoredAt: '2025-06-01',
        scope: 'technology',
        tensionIntent: null,
        contestedBy: ['gi-prog-teacher'],
        intent: {},
        evidence_required: ['tablet-pilot-results'],
      },
      {
        id: 'gi-prog-community',
        type: 'product_narrative',
        assertion: 'Community ownership of schools ensures programs survive beyond our involvement.',
        dependencies: ['gi-core-approach'],
        confidence: 1.0,
        author: 'Dr. Fatima Al-Rashid, Programs Director',
        authoredAt: '2024-03-01',
        scope: 'programs',
        tensionIntent: null,
        contestedBy: [],
        intent: {},
        evidence_required: [],
      },

      // ── Operational (2 units) ──
      {
        id: 'gi-ops-local-hire',
        type: 'operational',
        assertion: '90% of in-country staff are local hires — we invest in communities, not expat salaries.',
        dependencies: ['gi-core-approach', 'gi-pos-fundraising'],
        confidence: 0.95,
        author: 'Robert Kim, COO',
        authoredAt: '2024-04-01',
        scope: 'operations',
        tensionIntent: null,
        contestedBy: [],
        intent: {},
        evidence_required: [],
      },
      {
        id: 'gi-ops-reporting',
        type: 'operational',
        assertion: 'Quarterly impact reports published publicly with school-level outcome data.',
        dependencies: ['gi-pos-evidence'],
        confidence: 0.9,
        author: 'Dr. Amara Osei, Executive Director',
        authoredAt: '2024-05-01',
        scope: null,
        tensionIntent: null,
        contestedBy: [],
        intent: {},
        evidence_required: ['q4-impact-report'],
      },

      // ── Evidence (3 units, 1 unattributed) ──
      {
        id: 'gi-ev-outcomes',
        type: 'evidence',
        assertion: 'Students in partner schools score 34% higher on national exams after 2 years.',
        dependencies: ['gi-prog-teacher'],
        confidence: 1.0,
        author: 'Dr. Amara Osei, Executive Director',
        authoredAt: '2025-01-15',
        scope: null,
        tensionIntent: null,
        contestedBy: [],
        intent: {},
        evidence_required: [],
      },
      {
        id: 'gi-ev-retention',
        type: 'evidence',
        assertion: 'Teacher retention rate of 89% across partner schools vs. 52% national average.',
        dependencies: ['gi-prog-teacher', 'gi-ops-local-hire'],
        confidence: 0.95,
        author: 'Dr. Fatima Al-Rashid, Programs Director',
        authoredAt: '2025-01-15',
        scope: 'programs',
        tensionIntent: null,
        contestedBy: [],
        intent: {},
        evidence_required: [],
      },
      {
        id: 'gi-ev-tablet-pilot',
        type: 'evidence',
        assertion: 'Tablet pilot showed inconclusive results — connectivity issues in 40% of target schools.',
        dependencies: ['gi-prog-tech'],
        confidence: 0.6,
        author: null,
        authoredAt: null,
        scope: 'technology',
        tensionIntent: null,
        contestedBy: [],
        intent: {},
        evidence_required: ['tablet-pilot-full-report'],
      },

      // ── Communication (2 units, 1 deliberate tension) ──
      {
        id: 'gi-comm-annual',
        type: 'communication',
        assertion: 'Annual report centers student stories paired with outcome data — emotion backed by evidence.',
        dependencies: ['gi-pos-evidence', 'gi-ev-outcomes'],
        confidence: 1.0,
        author: 'Michelle Torres, VP Development',
        authoredAt: '2025-02-01',
        scope: 'fundraising',
        tensionIntent: null,
        contestedBy: [],
        intent: {},
        evidence_required: [],
      },
      {
        id: 'gi-comm-gala',
        type: 'communication',
        assertion: 'Gala messaging focuses on donor recognition and tax benefits over programmatic impact.',
        dependencies: ['gi-pos-fundraising'],
        confidence: 0.75,
        author: 'Michelle Torres, VP Development',
        authoredAt: '2025-09-01',
        scope: 'fundraising',
        tensionIntent: 'deliberate_tension',
        contestedBy: [],
        intent: { deliberate_tension: { reason: 'Fundraising events require different messaging than impact reports' } },
        evidence_required: [],
      },
    ],
  },
};

/**
 * Get demo data by type.
 * @param {string} type - 'saas' or 'nonprofit'
 * @returns {{ name: string, description: string, units: Array, skills: Object }}
 */
function getDemoData(type) {
  const demo = DEMOS[type];
  if (!demo) return null;
  return {
    name: demo.name,
    description: demo.description,
    units: demo.units.map(u => ({ ...u })), // shallow clone
    skills: JSON.parse(JSON.stringify(demo.skills)),
  };
}

/**
 * List available demos.
 * @returns {Array<{type: string, name: string, description: string, unitCount: number}>}
 */
function listDemos() {
  return Object.entries(DEMOS).map(([type, demo]) => ({
    type,
    name: demo.name,
    description: demo.description,
    unitCount: demo.units.length,
  }));
}

module.exports = { getDemoData, listDemos, DEMOS };
